"""
AI-QMS Phase 1 - Document Generation Component
Generate and download documents from Agent responses.

v2.4.8 - New file for document generation and download

This component allows agents to generate documents that users can download.
Documents are created as temporary files and served for download.
"""

import os
import tempfile
from pathlib import Path
from datetime import datetime
from typing import Optional, Dict, Any, List


# ============================================================
# Document Templates
# ============================================================

DOCUMENT_TEMPLATES = {
    "report": """---
title: {title}
type: Report
generated_at: {generated_at}
generated_by: AI-QMS Agent
---

# {title}

{content}

---
*This document was generated by AI-QMS Phase 1 Document Control System.*
*Generated at: {generated_at}*
""",
    "summary": """---
title: {title}
type: Summary
generated_at: {generated_at}
generated_by: AI-QMS Agent
---

# {title}

## Summary

{content}

---
*Generated by AI-QMS Phase 1*
""",
    "analysis": """---
title: {title}
type: Analysis
generated_at: {generated_at}
generated_by: AI-QMS Agent
---

# {title}

## Analysis Results

{content}

## Recommendations

{recommendations}

---
*Generated by AI-QMS Phase 1*
""",
    "plain": """{content}
""",
}


# ============================================================
# Functional API
# ============================================================


def build_markdown_document(
    content: str,
    title: Optional[str] = None,
    template: str = "plain",
    metadata: Optional[Dict[str, Any]] = None,
) -> str:
    """
    Build a Markdown document from content.

    Args:
        content: Main content of the document
        title: Document title (auto-generated if not provided)
        template: Template to use (report, summary, analysis, plain)
        metadata: Additional metadata to include

    Returns:
        Formatted Markdown document string
    """
    # Generate title if not provided
    if not title:
        title = f"Document_{datetime.now().strftime('%Y%m%d_%H%M%S')}"

    # Get template
    template_str = DOCUMENT_TEMPLATES.get(template, DOCUMENT_TEMPLATES["plain"])

    # Build document
    generated_at = datetime.now().isoformat()

    # Handle analysis template specially
    if template == "analysis":
        recommendations = (
            metadata.get("recommendations", "No recommendations provided.")
            if metadata
            else "No recommendations provided."
        )
        document = template_str.format(
            title=title,
            content=content,
            generated_at=generated_at,
            recommendations=recommendations,
        )
    else:
        document = template_str.format(
            title=title,
            content=content,
            generated_at=generated_at,
        )

    return document


def generate_document_file(
    content: str,
    filename: Optional[str] = None,
    title: Optional[str] = None,
    template: str = "plain",
    metadata: Optional[Dict[str, Any]] = None,
) -> str:
    """
    Generate a document file and return the path.

    Args:
        content: Main content of the document
        filename: Output filename (auto-generated if not provided)
        title: Document title
        template: Template to use
        metadata: Additional metadata

    Returns:
        Path to the generated file
    """
    # Build document content
    document = build_markdown_document(
        content=content,
        title=title,
        template=template,
        metadata=metadata,
    )

    # Generate filename if not provided
    if not filename:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"document_{timestamp}.md"

    # Ensure .md extension
    if not filename.endswith(".md"):
        filename += ".md"

    # Create temp file
    temp_dir = tempfile.gettempdir()
    file_path = Path(temp_dir) / filename

    # Write document
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(document)

    return str(file_path)


# ============================================================
# Document Generator Class
# ============================================================


class DocumentGenerator:
    """
    Document generator for creating downloadable documents from Agent responses.

    Usage:
        generator = DocumentGenerator()

        # Generate a simple document
        path = generator.generate("This is the content", title="My Report")

        # Generate with template
        path = generator.generate(
            content="Analysis results...",
            title="Analysis Report",
            template="analysis",
            metadata={"recommendations": "Improve X, Y, Z"}
        )
    """

    def __init__(self, output_dir: Optional[str] = None):
        """
        Initialize the document generator.

        Args:
            output_dir: Directory for output files (uses temp dir if not provided)
        """
        self.output_dir = (
            Path(output_dir) if output_dir else Path(tempfile.gettempdir())
        )
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(
        self,
        content: str,
        title: Optional[str] = None,
        filename: Optional[str] = None,
        template: str = "plain",
        metadata: Optional[Dict[str, Any]] = None,
    ) -> str:
        """
        Generate a document file.

        Args:
            content: Main content
            title: Document title
            filename: Output filename
            template: Template to use
            metadata: Additional metadata

        Returns:
            Path to the generated file
        """
        # Build document
        document = build_markdown_document(
            content=content,
            title=title,
            template=template,
            metadata=metadata,
        )

        # Generate filename
        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            safe_title = (title or "document").replace(" ", "_")[:30]
            filename = f"{safe_title}_{timestamp}.md"

        if not filename.endswith(".md"):
            filename += ".md"

        # Write file
        file_path = self.output_dir / filename
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(document)

        return str(file_path)

    def generate_from_chat(
        self,
        chat_history: List[Dict[str, Any]],
        title: Optional[str] = None,
        include_user_messages: bool = True,
    ) -> str:
        """
        Generate a document from chat history.

        Args:
            chat_history: List of chat messages
            title: Document title
            include_user_messages: Whether to include user messages

        Returns:
            Path to the generated file
        """
        # Build content from chat history
        content_parts = []

        for msg in chat_history:
            role = msg.get("role", "unknown")
            content = msg.get("content", "")

            if role == "user" and include_user_messages:
                content_parts.append(f"**User:** {content}\n")
            elif role == "assistant":
                content_parts.append(f"**Assistant:** {content}\n")

        content = "\n".join(content_parts)

        return self.generate(
            content=content,
            title=title or "Chat Export",
            template="report",
        )

    def generate_search_results(
        self,
        query: str,
        results: List[Dict[str, Any]],
        title: Optional[str] = None,
    ) -> str:
        """
        Generate a document from search results.

        Args:
            query: Search query
            results: Search results
            title: Document title

        Returns:
            Path to the generated file
        """
        content_parts = [f"## Search Query: {query}\n"]
        content_parts.append(f"Found {len(results)} results.\n")

        for i, result in enumerate(results, 1):
            content_parts.append(f"### {i}. {result.get('title', 'Untitled')}")
            content_parts.append(f"- **Document ID:** {result.get('doc_id', 'N/A')}")
            content_parts.append(f"- **Type:** {result.get('doc_type', 'N/A')}")
            content_parts.append(f"- **Version:** {result.get('version', 'N/A')}")
            if result.get("snippet"):
                content_parts.append(f"\n> {result['snippet']}\n")

        content = "\n".join(content_parts)

        return self.generate(
            content=content,
            title=title or f"Search Results: {query}",
            template="report",
        )


# ============================================================
# Module Test
# ============================================================

if __name__ == "__main__":
    print("Document Generation Component Test")
    print("=" * 50)

    # Test build_markdown_document
    print("\n1. Testing build_markdown_document...")
    doc = build_markdown_document(
        content="This is test content.",
        title="Test Document",
        template="report",
    )
    print(f"   Generated document ({len(doc)} chars)")

    # Test generate_document_file
    print("\n2. Testing generate_document_file...")
    path = generate_document_file(
        content="This is test content for file.",
        title="Test File",
        template="summary",
    )
    print(f"   Generated file: {path}")

    # Test DocumentGenerator class
    print("\n3. Testing DocumentGenerator class...")
    generator = DocumentGenerator()

    path = generator.generate(
        content="Analysis content here.",
        title="Analysis Report",
        template="analysis",
        metadata={"recommendations": "1. Do X\n2. Do Y"},
    )
    print(f"   Generated: {path}")

    # Test chat export
    print("\n4. Testing chat export...")
    chat_history = [
        {"role": "user", "content": "What is QMS?"},
        {"role": "assistant", "content": "QMS stands for Quality Management System."},
    ]
    path = generator.generate_from_chat(chat_history, title="QMS Discussion")
    print(f"   Generated: {path}")

    # Test search results export
    print("\n5. Testing search results export...")
    results = [
        {
            "doc_id": "SOP-001",
            "title": "Quality Manual",
            "doc_type": "SOP",
            "version": "1.0",
            "snippet": "This is the quality manual...",
        },
    ]
    path = generator.generate_search_results("quality", results)
    print(f"   Generated: {path}")

    print("\n" + "=" * 50)
    print("All tests passed!")
