"""
AI-QMS Phase 1 - 文件清單與全部紀錄匯出模組
Export document list (current formal versions) and all records to Word/Excel formats.
"""

from collections import defaultdict
from datetime import datetime
from pathlib import Path

from docx import Document
from docx.shared import Pt, Cm, RGBColor
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side


# Output directory for generated files
EXPORT_DIR = Path("data/exports")
EXPORT_DIR.mkdir(parents=True, exist_ok=True)

# i18n UI strings
_DOCLIST_UI = {
    "zh": {
        "title": "AI-QMS 文件清單報告 (現行正式版本)",
        "export_time": "匯出時間",
        "total_docs": "文件總數",
        "unit": "份",
        "no_docs": "目前沒有現行有效的正式文件。",
        "headers": ["#", "文件編號", "標題", "類型", "現行版本", "下載次數", "下載者（最近5筆）"],
        "footer": "本報告由 AI-QMS 品質管理系統自動產生。",
        "sheet": "文件清單",
        "obsolete": "已作廢",
        "superseded": "已進版",
        "current": "現行版",
    },
    "en": {
        "title": "AI-QMS Document List Report (Current Formal Versions)",
        "export_time": "Export Time",
        "total_docs": "Total Documents",
        "unit": "",
        "no_docs": "No current formal documents found.",
        "headers": ["#", "Document ID", "Title", "Type", "Current Version", "Downloads", "Recent Downloaders"],
        "footer": "This report was automatically generated by AI-QMS Quality Management System.",
        "sheet": "Document List",
        "obsolete": "Obsolete",
        "superseded": "Superseded",
        "current": "Current",
        "allrecords_title": "AI-QMS All Document Records Report",
        "allrecords_sheet": "All Records",
        "docs_count": "Documents",
        "version_records": "Version Records",
        "active": "Active",
        "no_records": "No document records found.",
        "allrecords_headers": ["#", "Document ID", "Title", "Type", "Version", "Date", "Operator", "Status", "Downloads", "Recent Downloaders"],
        "allrecords_footer": "This report was automatically generated by AI-QMS. Records are protected by SHA-256 hash chain for data integrity.",
    },
}
_DOCLIST_UI["zh"]["allrecords_title"] = "AI-QMS 全部文件紀錄報告"
_DOCLIST_UI["zh"]["allrecords_sheet"] = "全部文件紀錄"
_DOCLIST_UI["zh"]["docs_count"] = "文件數"
_DOCLIST_UI["zh"]["version_records"] = "版本紀錄"
_DOCLIST_UI["zh"]["active"] = "有效"
_DOCLIST_UI["zh"]["no_records"] = "目前沒有任何文件紀錄。"
_DOCLIST_UI["zh"]["allrecords_headers"] = ["#", "文件編號", "標題", "類型", "版本", "日期", "操作者", "狀態", "下載次數", "下載者（最近5筆）"]
_DOCLIST_UI["zh"]["allrecords_footer"] = "本報告由 AI-QMS 品質管理系統自動產生。文件更動紀錄受 SHA-256 雜湊鏈保護，確保資料完整性與不可竄改。"


def _dl_ui(lang: str) -> dict:
    return _DOCLIST_UI["zh"] if lang.startswith("zh") else _DOCLIST_UI["en"]

# Shared Excel styles
THIN_BORDER = Border(
    left=Side(style="thin"),
    right=Side(style="thin"),
    top=Side(style="thin"),
    bottom=Side(style="thin"),
)


# ============================================================
# Download stats helper
# ============================================================


def _build_download_stats(audit_records: list) -> dict:
    """Build a per-doc_id download summary from DOC_DOWNLOADED audit records.

    Returns:
        dict mapping doc_id → {"count": int, "recent": str}
        where "recent" is a comma-joined list of the last 5 downloader names.
    """
    counts: dict = defaultdict(int)
    downloaders: dict = defaultdict(list)

    for r in audit_records:
        if r.get("action") == "DOC_DOWNLOADED":
            doc_id = r.get("document_id", "")
            user = r.get("user_id", "")
            if doc_id:
                counts[doc_id] += 1
                if user:
                    downloaders[doc_id].append(user)

    stats = {}
    for doc_id in set(list(counts.keys()) + list(downloaders.keys())):
        recent_5 = downloaders[doc_id][-5:]
        stats[doc_id] = {
            "count": counts[doc_id],
            "recent": ", ".join(recent_5) if recent_5 else "",
        }
    return stats


# ============================================================
# 文件清單 (Document List — Current Formal Versions)
# ============================================================


def export_doclist_to_word(docs: list, download_stats: dict | None = None, lang: str = "zh-TW") -> str:
    """
    Export current formal document list to a Word (.docx) file.

    Args:
        docs: List of active document dicts with doc_id, title, doc_type, current_version.

    Returns:
        Path to the generated .docx file.
    """
    ui = _dl_ui(lang)
    doc = Document()

    # Title
    title = doc.add_heading(ui["title"], level=1)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Metadata
    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    run = meta.add_run(f"{ui['export_time']}: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor(128, 128, 128)

    meta2 = doc.add_paragraph()
    meta2.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    run2 = meta2.add_run(f"{ui['total_docs']}: {len(docs)} {ui['unit']}")
    run2.font.size = Pt(9)
    run2.font.color.rgb = RGBColor(128, 128, 128)

    doc.add_paragraph()  # spacer

    if not docs:
        doc.add_paragraph(ui["no_docs"])
    else:
        dl_stats = download_stats or {}

        # Create table
        table = doc.add_table(rows=1, cols=7)
        table.style = "Table Grid"
        table.alignment = WD_TABLE_ALIGNMENT.CENTER

        # Header row
        headers = ui["headers"]
        for i, header in enumerate(headers):
            cell = table.rows[0].cells[i]
            cell.text = header
            for paragraph in cell.paragraphs:
                paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
                for run in paragraph.runs:
                    run.font.bold = True
                    run.font.size = Pt(9)

        # Data rows
        for idx, d in enumerate(docs, 1):
            row = table.add_row()
            doc_id = d.get("doc_id", "")
            stat = dl_stats.get(doc_id, {})
            values = [
                str(idx),
                doc_id,
                d.get("title", "N/A"),
                d.get("doc_type", "OTHER"),
                f"v{d.get('current_version', '?')}",
                str(stat.get("count", 0)),
                stat.get("recent", ""),
            ]
            for i, val in enumerate(values):
                cell = row.cells[i]
                cell.text = val
                for paragraph in cell.paragraphs:
                    for run in paragraph.runs:
                        run.font.size = Pt(8)

        # Set column widths
        widths = [Cm(0.8), Cm(2.5), Cm(5), Cm(2), Cm(2), Cm(1.5), Cm(4)]
        for row in table.rows:
            for i, width in enumerate(widths):
                row.cells[i].width = width

    # Footer
    doc.add_paragraph()
    footer = doc.add_paragraph()
    run = footer.add_run(ui["footer"])
    run.font.size = Pt(8)
    run.font.italic = True
    run.font.color.rgb = RGBColor(128, 128, 128)

    # Save
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"doclist_{timestamp}.docx"
    filepath = EXPORT_DIR / filename
    doc.save(str(filepath))
    return str(filepath)


def export_doclist_to_excel(docs: list, download_stats: dict | None = None, lang: str = "zh-TW") -> str:
    """
    Export current formal document list to an Excel (.xlsx) file.

    Args:
        docs: List of active document dicts with doc_id, title, doc_type, current_version.

    Returns:
        Path to the generated .xlsx file.
    """
    ui = _dl_ui(lang)
    wb = Workbook()
    ws = wb.active
    ws.title = ui["sheet"]

    # Styles
    header_font = Font(name="Microsoft JhengHei", bold=True, size=10, color="FFFFFF")
    header_fill = PatternFill(
        start_color="1F6F3D", end_color="1F6F3D", fill_type="solid"
    )
    header_alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    cell_font = Font(name="Microsoft JhengHei", size=9)
    cell_alignment = Alignment(vertical="center", wrap_text=True)

    dl_stats = download_stats or {}

    # Title row
    ws.merge_cells("A1:G1")
    title_cell = ws["A1"]
    title_cell.value = ui["title"]
    title_cell.font = Font(name="Microsoft JhengHei", bold=True, size=14)
    title_cell.alignment = Alignment(horizontal="center")

    # Metadata row
    ws.merge_cells("A2:G2")
    meta_cell = ws["A2"]
    meta_cell.value = (
        f"{ui['export_time']}: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | "
        f"{ui['total_docs']}: {len(docs)} {ui['unit']}"
    )
    meta_cell.font = Font(name="Microsoft JhengHei", size=9, color="808080")
    meta_cell.alignment = Alignment(horizontal="right")

    # Headers (row 4)
    xl_headers = ui["headers"]
    for col, header in enumerate(xl_headers, 1):
        cell = ws.cell(row=4, column=col, value=header)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_alignment
        cell.border = THIN_BORDER

    # Data rows
    for idx, d in enumerate(docs, 1):
        row_num = idx + 4
        doc_id = d.get("doc_id", "")
        stat = dl_stats.get(doc_id, {})
        values = [
            idx,
            doc_id,
            d.get("title", "N/A"),
            d.get("doc_type", "OTHER"),
            f"v{d.get('current_version', '?')}",
            stat.get("count", 0),
            stat.get("recent", ""),
        ]
        for col, val in enumerate(values, 1):
            cell = ws.cell(row=row_num, column=col, value=val)
            cell.font = cell_font
            cell.alignment = cell_alignment
            cell.border = THIN_BORDER

    # Column widths
    col_widths = [5, 15, 35, 12, 12, 10, 30]
    for i, width in enumerate(col_widths, 1):
        ws.column_dimensions[chr(64 + i)].width = width

    # Freeze header row
    ws.freeze_panes = "A5"

    # Footer note
    note_row = len(docs) + 6
    ws.merge_cells(f"A{note_row}:G{note_row}")
    note_cell = ws.cell(row=note_row, column=1)
    note_cell.value = ui["footer"]
    note_cell.font = Font(
        name="Microsoft JhengHei", size=8, italic=True, color="808080"
    )

    # Save
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"doclist_{timestamp}.xlsx"
    filepath = EXPORT_DIR / filename
    wb.save(str(filepath))
    return str(filepath)


# ============================================================
# 全部文件紀錄 (All Records — incl. version history & obsolete)
# ============================================================


def _compute_status(doc: dict, ver_entry: dict, lang: str = "zh-TW") -> str:
    """Compute display status for a version entry."""
    ui = _dl_ui(lang)
    status_str = doc.get("status", "active")
    current_ver = doc.get("current_version", "?")
    ver = ver_entry.get("version", "?")
    files_removed = ver_entry.get("files_removed", False)

    if status_str == "obsolete":
        return ui["obsolete"]
    elif files_removed:
        return ui["superseded"]
    elif ver == current_ver:
        return ui["current"]
    else:
        return ui["superseded"]


def export_allrecords_to_word(all_docs: list, download_stats: dict | None = None, lang: str = "zh-TW") -> str:
    """
    Export all document records (incl. version history, obsolete) to Word (.docx).

    Args:
        all_docs: Full documents list from registry["documents"].

    Returns:
        Path to the generated .docx file.
    """
    ui = _dl_ui(lang)
    doc = Document()

    # Title
    title = doc.add_heading(ui["allrecords_title"], level=1)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Metadata
    total_versions = sum(len(d.get("versions", [])) for d in all_docs)
    active_count = sum(1 for d in all_docs if d.get("status", "active") == "active")
    obsolete_count = sum(1 for d in all_docs if d.get("status") == "obsolete")

    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    run = meta.add_run(f"{ui['export_time']}: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor(128, 128, 128)

    meta2 = doc.add_paragraph()
    meta2.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    run2 = meta2.add_run(
        f"{ui['docs_count']}: {len(all_docs)} {ui['unit']} | {ui['version_records']}: {total_versions} | "
        f"{ui['active']}: {active_count} | {ui['obsolete']}: {obsolete_count}"
    )
    run2.font.size = Pt(9)
    run2.font.color.rgb = RGBColor(128, 128, 128)

    doc.add_paragraph()  # spacer

    dl_stats = download_stats or {}

    if not all_docs:
        doc.add_paragraph(ui["no_records"])
    else:
        # Create table
        table = doc.add_table(rows=1, cols=10)
        table.style = "Table Grid"
        table.alignment = WD_TABLE_ALIGNMENT.CENTER

        # Header row
        headers = ui["allrecords_headers"]
        for i, header in enumerate(headers):
            cell = table.rows[0].cells[i]
            cell.text = header
            for paragraph in cell.paragraphs:
                paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
                for run in paragraph.runs:
                    run.font.bold = True
                    run.font.size = Pt(9)

        # Data rows
        row_idx = 0
        for d in all_docs:
            doc_id = d.get("doc_id", "")
            title_text = d.get("title", "N/A")
            doc_type = d.get("doc_type", "OTHER")
            stat = dl_stats.get(doc_id, {})

            for ver_entry in d.get("versions", []):
                row_idx += 1
                row = table.add_row()
                ver = ver_entry.get("version", "?")
                created_at = ver_entry.get("created_at", "")[:10]
                created_by = ver_entry.get("created_by", "system")
                status = _compute_status(d, ver_entry, lang)

                values = [
                    str(row_idx),
                    doc_id,
                    title_text,
                    doc_type,
                    f"v{ver}",
                    created_at,
                    created_by,
                    status,
                    str(stat.get("count", 0)),
                    stat.get("recent", ""),
                ]
                for i, val in enumerate(values):
                    cell = row.cells[i]
                    cell.text = val
                    for paragraph in cell.paragraphs:
                        for run in paragraph.runs:
                            run.font.size = Pt(8)

        # Set column widths
        widths = [Cm(0.6), Cm(2), Cm(3.5), Cm(1.5), Cm(1), Cm(2), Cm(1.5), Cm(1.5), Cm(1.2), Cm(3)]
        for row in table.rows:
            for i, width in enumerate(widths):
                row.cells[i].width = width

    # Footer
    doc.add_paragraph()
    footer = doc.add_paragraph()
    run = footer.add_run(ui["allrecords_footer"])
    run.font.size = Pt(8)
    run.font.italic = True
    run.font.color.rgb = RGBColor(128, 128, 128)

    # Save
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"allrecords_{timestamp}.docx"
    filepath = EXPORT_DIR / filename
    doc.save(str(filepath))
    return str(filepath)


def export_allrecords_to_excel(all_docs: list, download_stats: dict | None = None, lang: str = "zh-TW") -> str:
    """
    Export all document records to an Excel (.xlsx) file.

    Args:
        all_docs: Full documents list from registry["documents"].

    Returns:
        Path to the generated .xlsx file.
    """
    ui = _dl_ui(lang)
    wb = Workbook()
    ws = wb.active
    ws.title = ui["allrecords_sheet"]

    # Styles
    header_font = Font(name="Microsoft JhengHei", bold=True, size=10, color="FFFFFF")
    header_fill = PatternFill(
        start_color="7B2D8E", end_color="7B2D8E", fill_type="solid"
    )
    header_alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    cell_font = Font(name="Microsoft JhengHei", size=9)
    cell_alignment = Alignment(vertical="center", wrap_text=True)

    # Count stats
    total_versions = sum(len(d.get("versions", [])) for d in all_docs)
    active_count = sum(1 for d in all_docs if d.get("status", "active") == "active")
    obsolete_count = sum(1 for d in all_docs if d.get("status") == "obsolete")

    dl_stats = download_stats or {}

    # Title row
    ws.merge_cells("A1:J1")
    title_cell = ws["A1"]
    title_cell.value = ui["allrecords_title"]
    title_cell.font = Font(name="Microsoft JhengHei", bold=True, size=14)
    title_cell.alignment = Alignment(horizontal="center")

    # Metadata row
    ws.merge_cells("A2:J2")
    meta_cell = ws["A2"]
    meta_cell.value = (
        f"{ui['export_time']}: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | "
        f"{ui['docs_count']}: {len(all_docs)} {ui['unit']} | {ui['version_records']}: {total_versions} | "
        f"{ui['active']}: {active_count} | {ui['obsolete']}: {obsolete_count}"
    )
    meta_cell.font = Font(name="Microsoft JhengHei", size=9, color="808080")
    meta_cell.alignment = Alignment(horizontal="right")

    # Headers (row 4)
    xl_headers = ui["allrecords_headers"]
    for col, header in enumerate(xl_headers, 1):
        cell = ws.cell(row=4, column=col, value=header)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_alignment
        cell.border = THIN_BORDER

    # Data rows
    row_idx = 0
    for d in all_docs:
        doc_id = d.get("doc_id", "")
        title_text = d.get("title", "N/A")
        doc_type = d.get("doc_type", "OTHER")
        stat = dl_stats.get(doc_id, {})

        for ver_entry in d.get("versions", []):
            row_idx += 1
            row_num = row_idx + 4
            ver = ver_entry.get("version", "?")
            created_at = ver_entry.get("created_at", "")[:10]
            created_by = ver_entry.get("created_by", "system")
            status = _compute_status(d, ver_entry, lang)

            values = [
                row_idx,
                doc_id,
                title_text,
                doc_type,
                f"v{ver}",
                created_at,
                created_by,
                status,
                stat.get("count", 0),
                stat.get("recent", ""),
            ]
            for col, val in enumerate(values, 1):
                cell = ws.cell(row=row_num, column=col, value=val)
                cell.font = cell_font
                cell.alignment = cell_alignment
                cell.border = THIN_BORDER

    # Column widths
    col_widths = [5, 15, 30, 12, 10, 15, 12, 12, 10, 30]
    for i, width in enumerate(col_widths, 1):
        ws.column_dimensions[chr(64 + i)].width = width

    # Freeze header row
    ws.freeze_panes = "A5"

    # Footer note
    note_row = row_idx + 6
    ws.merge_cells(f"A{note_row}:J{note_row}")
    note_cell = ws.cell(row=note_row, column=1)
    note_cell.value = ui["allrecords_footer"]
    note_cell.font = Font(
        name="Microsoft JhengHei", size=8, italic=True, color="808080"
    )

    # Save
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"allrecords_{timestamp}.xlsx"
    filepath = EXPORT_DIR / filename
    wb.save(str(filepath))
    return str(filepath)
